### ISSUE TITLE
Next major

### ISSUE THREAD

**Issue by SimenB** [jest-community/eslint-plugin-jest#1210]
I'm thinking it's about time to make a new release dropping node 12 (and 17) and eslint 6 so that we can update our dev deps. @G-Rath any other breaking changes you wanna get it at the same time?

**Comment by G-Rath** [comment]
Yup:
  * https://github.com/jest-community/eslint-plugin-jest/issues/1172: I don't think it's breaking per say, but if we're doing a new major might as well include it
  * https://github.com/jest-community/eslint-plugin-jest/issues/1156#issuecomment-1160825857: I think changing the behaviour to be an entire matcher makes better sense in the long run because it gives more flexibility and it just means you need to repeat a couple of lines which can easily be done with `.map` and shouldn't need updating so not really an extra burden
    * technically we could then remove `prefer-called-with`, though I'm hesitant as it makes it a little harder to use in shared configs (since if teams decide to use `no-restricted-matchers` they have to make sure to apply the config from the shared config too)
  * we should talk about what we do with `no-jest-import` now that we've got support for `@jest/globals` - I think tossing it is probably the right thing to do? https://github.com/jest-community/eslint-plugin-jest/pull/1169#issuecomment-1193380757 (we could always reuse the name later)

I think that's all the breaking stuff, but will do a double check this week.

Also how would you feel if I made an issue over on Jest pushing (again) for removing the alised matchers, given we've got `no-alias-methods` as an autofix? then we could remove or deprecate that rule here in favor of `no-restricted-matchers` or even `no-deprecated-functions` (either in this major or the next).

**Comment by SimenB** [comment]
All those sounds good to me!

Happy to remove aliased matchers in _next_ major of jest (30), but not the imminent 29 (this week)

**Comment by G-Rath** [comment]
Cool - 30 is a nice round number anyway 😄 I'll make an issue on Jest and do follow up stuff later this week. Do you want to get a `next` branch going?

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest/tree/next

**Comment by G-Rath** [comment]
Have created https://github.com/facebook/jest/issues/13164

**Comment by G-Rath** [comment]
@SimenB I think we should add `no-alias-methods` to recommended since we're going to remove from Jest "soon" (technically they're deprecated functions but iirc `no-deprecated-functions` is not yet setup for `expect` matchers - I guess we should think about what we want to do for that)

**Comment by SimenB** [comment]
works for me 👍

**Comment by G-Rath** [comment]
@SimenB I just remembered about #292 - it seems to me like we shouldn't need our snapshot processor anymore, so we could delete it in this major.

**Comment by SimenB** [comment]
Not sure about that one... It's unclear to me what we should do, and I don't think we should block a new release on it. Easy enough to just go with a new major if needed 🙂

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v27.0.0
