### ISSUE TITLE
Consider splitting out a generalized testing plugin

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jest-community/eslint-plugin-jest#1289]
Hi! I'm a big fan of this plugin and have been using it for a while. But I recently switched some projects to [Vitest](https://vitest.dev) and not all the rules in this plugin apply quite the same in Vitest (e.g. [`no-jasmine-globals`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-jasmine-globals.md)).

[`eslint-plugin-vitest`](https://github.com/veritem/eslint-plugin-vitest) exists, with some duplication of rule logic. It's much newer, though, and has fewer rules implemented & a much smaller commmunity.

What do you think about us extracting out the rules from these two plugins into a shared plugin, like `eslint-plugin-tests`, that's meant to work for the common style of testing libraries in JS/TS today? I'm a maintainer on typescript-eslint and am confident I can help or lead this if you want. 😄 

cc @veritem from `eslint-plugin-vitest` 👋

**Comment by mrazauskas** [comment]
Sounds interesting. How do you imagine the usage? Should user add both `eslint-plugin-tests` and `eslint-plugin-jest` to ESLint config?

I am asking, because this could be useful for one of mine work-in-progress project too. It has Jest style API and could reuse many rules. (Only API is similar, but that is not one more Jest like testing framework.)

**Comment by mrazauskas** [comment]
Can it be a library which is exporting a set of common rules, which could be imported and used by each framework specific plugin? This way users will not notice any difference.

Only question: does ESLint plugin architecture allow this? I don't have much experience in the field. You are the expert here (;

**Comment by bmish** [comment]
I have definitely seen overlap in lint rules for different test frameworks. Many best practices are the same regardless of the test framework. So I know ESLint plugins for different test frameworks already take inspiration from each other's rules on occasion or otherwise end up with some similar rules (in particular, I work on [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) and this has been the case).

However, I do worry that trying to share rules between testing frameworks would increase complexity too much. There are obviously syntax/naming/behavior differences between testing frameworks that each lint rule would have to handle. It can already be challenging just trying to ensure a lint rule handles different major versions of a single testing framework (especially with occasional breaking changes), and so trying to handle multiple testing frameworks in the same rule would add yet another dimension to the matrix of scenarios to handle. And just imagine trying to test and document each rule in such a way that it covers every possible testing framework...that's a lot of maintenance overhead and complexity vs. just having a single, light-weight, focused rule per test framework (the `no-focused-tests` rule is pretty simple as-is). Rules that try to do too much can become unmanageable in my experience.

**Comment by mrazauskas** [comment]
Programmatic API would be harder to implement, but it would allow more flexibility. For example, `"no-deprecated-functions"` rule could be build on top of shared logic using framework specific list of deprecated APIs; or having custom rule name would be useful for `"jest/no-restricted-jest-methods"` and `"vitest/no-restricted-vitest-methods"` (can be this one is not yet implemented).

**Comment by G-Rath** [comment]
So I've thought about this in the past (especially when I started being involved in maintaining `eslint-plugin-jest-dom`, among other things), and overall came the conclusion that while it seems like a really good and useful idea on the face, in practice there's not a whole lot of gain vs the huge potential complexities because of how different core features can be handled in testing frameworks, and that rules typically stabilize very quickly so I wouldn't expect you would need to be sinking a lot of effort into keeping a copied rule up to date.

This has also been the reason why I've not pulled [the utilities](https://github.com/jest-community/eslint-plugin-jest/tree/main/src/rules/utils) out into their own package*, because while they look like they'd be useful across a bunch of plugins, everyone has a slightly different implementations which would mean having to get buy-in from the plugin maintainers to potentially refactor their rules heavily, when their existing implementations work fine and generally have a low footprint so it doesn't feel like there's a strong enough gain to be worth the effort it'll require...

So yeah, for me whenever I've thought about this I'm ended up at "this feels like a lot of work for something that doesn't really fix anything that's broken"

*: this will probably happen at some point for `parseJestFn` and friends because `eslint-plugin-jest`, `eslint-plugin-jest-dom`, and `eslint-plugin-jest-extended` should all be resolving `jest` functions with that, but I've got to review `eslint-plugin-jest-dom` first as that currently uses selectors very heavily.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
