### ISSUE TITLE
`prefer-spy-on` should ignore `jest.fn` outside of `test` blocks

### ISSUE THREAD

**Issue by garyking** [jest-community/eslint-plugin-jest#209]
Per [this](https://github.com/jest-community/eslint-plugin-jest/issues/185#issuecomment-439673024), the new rule should not recommend replacing `jest.fn` with `jest.spyOn` when used outside of `test` blocks, since `jest.spyOn` can't even be used outside of test blocks.

**Comment by G-Rath** [comment]
I've put a similar comment on your PR, but felt I should also make a comment here, just as this feels like the better place to discuss the overarching issue:

Personally I feel this is a problem with your file scoping, rather than with the rule itself.

This plugin is targeted at linting files that are considered "jest tests", and so assumes anything it's given is based within a test suite.

If we can't assume that, we've have to have some way of figuring out if a file is a test suite or not, which would mean making an arbitrary choice that I'm sure won't work for every possible variation you could have.

As such, I think that rather than change how the rule works, I think the better solution is to adjust what files the rules are being applied to, which you can do using either overrides or nested configs.

-----

In saying that, I don't know every possible variation of code you could have, and based on the [comments about `undefined`](https://github.com/jest-community/eslint-plugin-jest/issues/185#issuecomment-442434229) I think it would make sense to look to have an exclusion option :)

**Comment by garyking** [comment]
Okay I guess targeting test files is the only way to do this then.

**Comment by G-Rath** [comment]
I still think it's good that we have this issue & discussion on record, so cheers for that :)

Just so it's here for anyone who finds their way to this issue, heres an example of how you could disable the rule for `__mocks__`:

```
`eslint` is more than equipped to handle disabling rules on a per-file/path basis, but it's designed to do so at the config level, rather than at the rule level:

```
  "overrides": [
    {
      "files": ["*/__mocks__/*"],
      "rules": {
        "jest/prefer-spy-on": "off"
      }
    }
  ],
```

**Comment by garyking** [comment]
With this `files` setting, if `__mocks__` is in the project's root dir, then it won't match this `override`. Is there a way to match those, while still matching `__mocks__` dirs in subdirs?

**Comment by G-Rath** [comment]
You can use multiple patterns yes, but you should also be able to cover it w/ a single glob pattern, which I thought mine should do...

You might need `**` instead of `*` - my globbing isn't super strong; it otherwise could just be b/c of the paths being used you have to account for `/*/__mocks__/` somehow (if that makes sense).

Eitherway, using multiple patterns will definitely cover it :)

**Comment by garyking** [comment]
Yeah I decided to use `files: ['**/__mocks__/*.js'],`.
