### ISSUE TITLE
[expect-expect] reports the entire test as erroneous

### ISSUE THREAD

**Issue by DanielSWolf** [jest-community/eslint-plugin-jest#539]
Within each unit test, the actual `expect` statement usually follows some amount of setup. As long as I'm writing this setup code, the test is technically invalid according to the `expect-expect` rule because it doesn't include any `expect`s. However, this means that about 80% of the time I spend writing unit tests, the entire function I'm writing is disfigured with red squigglies:

![image](https://user-images.githubusercontent.com/5963162/75225896-b66f6800-57ab-11ea-80c1-f0cb4c0bdc3d.png)

This doesn't just look bad. It also hides any actual errors I may have made. Only when I type the first `expect` do I see whether there are any other problems with my code.

Would it be possible for this rule to report *only part* of the test function as erroneous? For instance, just the `it`? Here's a mockup of how this might look:

![image](https://user-images.githubusercontent.com/5963162/75227433-78277800-57ae-11ea-8455-8fa774ad6efb.png)

**Comment by G-Rath** [comment]
@DanielSWolf the `it` node is the node we report as erroneous.

You'll want to create a new issue for your editor, as we don't control how the errors are rendered.

For reference, IntelliJ/WebStorm does render the error as you'd like:

![image](https://user-images.githubusercontent.com/3151613/75231931-34b72300-581b-11ea-8582-fa1ee619538b.png)

To be honest, I'd like to report the callback rather than the `it` node, as it's a pretty overloaded node (in the screenshot above, there are four errors on it).
