### ISSUE TITLE
`lowercase-name` rule `ignoreTopLevelTest` option

### ISSUE THREAD

**Issue by overlookmotel** [jest-community/eslint-plugin-jest#612]
To complement the `ignoreTopLevelDescribe` option added in #611, would it be possible to also have an `ignoreTopLevelTest` option?

I'd envisage it affecting both `it` and `test` - I doubt many people use both `it` and `test` in the same file, so it seems excessive to have separate `ignoreTopLevelTest` and `ignoreTopLevelIt` options.

An additional option `ignoreTopLevel` could also set both `ignoreTopLevelDescribe` and `ignoreTopLevelTest`.

Does this sound like a feature you'd accept? If so, I'd be happy to do a PR based on #611.

**Comment by G-Rath** [comment]
I don't feel like this makes sense, as the whole idea behind `lowercase-name` is about encouraging sentences that make grammatical sense; the reason we have `ignoreTopLevelDescribe` is because describe blocks "describe" things, and things like classes & react components start with a capital letter.

However, `test` & `it` are the start of a sentence, and so there's no common grammatical correct sentence that has the second word starting with a capital, except maybe "`test('MyClass to ensure it does the thing')`, which I feel would be better wrapped in a describe anyway.

**Comment by overlookmotel** [comment]
I guess it depends on how you write you test "sentences". I typically test that a library's exports are exported as intended, with something like this:

```js
test( 'MyClass is a function', () => {
  expect( typeof MyClass ).toBe('function');
} );
```

Does that seem like a reasonable case to you?

**Comment by G-Rath** [comment]
That makes sense, but I'm still lukewarm on adding a new option for this as I feel it leads to adding more options that are starting to miss the point of the rule.

In your case, you can make `lowercase-name` happy by just starting with `that`:

```
import { MyClass } from 'my-library';

test( 'that MyClass is a function', () => {
  expect( typeof MyClass ).toBe('function');
} );
```

`describe` is considered an exception for this because it's a lot harder to come up with a good, grammatical correct title that is not long winded for wrapping things whose names are in PascelCase; i.e:

```
describe('MyClass', () => {
  describe('#myMethod', () => {
    it('returns the right value', () =>{
      // ...
    });
  });
});
```

In the above, there isn't really a nice way to structure the title to have a lowercase name that reads correctly and doesn't require using a different structure to other tests for things like functions:

 * "[describe] that MyClass",
 * "[describe] the class",
 * "[describe] the methods in MyClass"

**Comment by G-Rath** [comment]
I'm going to close this off due to the reasons outlined in my previous comment.
